//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SMSContext", "DISH_TYPEDISH", "DISH_TYPE", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.DISH_TYPE), "DISH", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.DISH), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "STATUSPROCESSING", "STATUS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.STATUS), "PROCESSING", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.PROCESSING), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "TABLES_INFOPROCESSING", "TABLES_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.TABLES_INFO), "PROCESSING", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.PROCESSING), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "WAITER_INFOTABLES_INFO", "WAITER_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.WAITER_INFO), "TABLES_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.TABLES_INFO), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "BILLINGBILLING_DETAIL", "BILLING", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.BILLING), "BILLING_DETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.BILLING_DETAIL), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "TABLES_INFOBILLING", "TABLES_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.TABLES_INFO), "BILLING", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.BILLING), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "DISHBILLING_DETAIL", "DISH", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.DISH), "BILLING_DETAIL", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.BILLING_DETAIL), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "CHEF_INFOBILLING", "CHEF_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.CHEF_INFO), "BILLING", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.BILLING), true)]
[assembly: EdmRelationshipAttribute("SMSContext", "CHEF_INFOPROCESSING", "CHEF_INFO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SMS_Management.CHEF_INFO), "PROCESSING", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SMS_Management.PROCESSING), true)]

#endregion

namespace SMS_Management
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SMS_DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SMS_DatabaseEntities object using the connection string found in the 'SMS_DatabaseEntities' section of the application configuration file.
        /// </summary>
        public SMS_DatabaseEntities() : base("name=SMS_DatabaseEntities", "SMS_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMS_DatabaseEntities object.
        /// </summary>
        public SMS_DatabaseEntities(string connectionString) : base(connectionString, "SMS_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SMS_DatabaseEntities object.
        /// </summary>
        public SMS_DatabaseEntities(EntityConnection connection) : base(connection, "SMS_DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CHEF_INFO> CHEF_INFO
        {
            get
            {
                if ((_CHEF_INFO == null))
                {
                    _CHEF_INFO = base.CreateObjectSet<CHEF_INFO>("CHEF_INFO");
                }
                return _CHEF_INFO;
            }
        }
        private ObjectSet<CHEF_INFO> _CHEF_INFO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CURENCY_TYPE> CURENCY_TYPE
        {
            get
            {
                if ((_CURENCY_TYPE == null))
                {
                    _CURENCY_TYPE = base.CreateObjectSet<CURENCY_TYPE>("CURENCY_TYPE");
                }
                return _CURENCY_TYPE;
            }
        }
        private ObjectSet<CURENCY_TYPE> _CURENCY_TYPE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DISH> DISHes
        {
            get
            {
                if ((_DISHes == null))
                {
                    _DISHes = base.CreateObjectSet<DISH>("DISHes");
                }
                return _DISHes;
            }
        }
        private ObjectSet<DISH> _DISHes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DISH_TYPE> DISH_TYPE
        {
            get
            {
                if ((_DISH_TYPE == null))
                {
                    _DISH_TYPE = base.CreateObjectSet<DISH_TYPE>("DISH_TYPE");
                }
                return _DISH_TYPE;
            }
        }
        private ObjectSet<DISH_TYPE> _DISH_TYPE;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PROCESSING> PROCESSINGs
        {
            get
            {
                if ((_PROCESSINGs == null))
                {
                    _PROCESSINGs = base.CreateObjectSet<PROCESSING>("PROCESSINGs");
                }
                return _PROCESSINGs;
            }
        }
        private ObjectSet<PROCESSING> _PROCESSINGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<STATUS> STATUS
        {
            get
            {
                if ((_STATUS == null))
                {
                    _STATUS = base.CreateObjectSet<STATUS>("STATUS");
                }
                return _STATUS;
            }
        }
        private ObjectSet<STATUS> _STATUS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TABLES_INFO> TABLES_INFO
        {
            get
            {
                if ((_TABLES_INFO == null))
                {
                    _TABLES_INFO = base.CreateObjectSet<TABLES_INFO>("TABLES_INFO");
                }
                return _TABLES_INFO;
            }
        }
        private ObjectSet<TABLES_INFO> _TABLES_INFO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WAITER_INFO> WAITER_INFO
        {
            get
            {
                if ((_WAITER_INFO == null))
                {
                    _WAITER_INFO = base.CreateObjectSet<WAITER_INFO>("WAITER_INFO");
                }
                return _WAITER_INFO;
            }
        }
        private ObjectSet<WAITER_INFO> _WAITER_INFO;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BILLING> BILLINGs
        {
            get
            {
                if ((_BILLINGs == null))
                {
                    _BILLINGs = base.CreateObjectSet<BILLING>("BILLINGs");
                }
                return _BILLINGs;
            }
        }
        private ObjectSet<BILLING> _BILLINGs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BILLING_DETAIL> BILLING_DETAIL
        {
            get
            {
                if ((_BILLING_DETAIL == null))
                {
                    _BILLING_DETAIL = base.CreateObjectSet<BILLING_DETAIL>("BILLING_DETAIL");
                }
                return _BILLING_DETAIL;
            }
        }
        private ObjectSet<BILLING_DETAIL> _BILLING_DETAIL;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CHEF_INFO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCHEF_INFO(CHEF_INFO cHEF_INFO)
        {
            base.AddObject("CHEF_INFO", cHEF_INFO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CURENCY_TYPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCURENCY_TYPE(CURENCY_TYPE cURENCY_TYPE)
        {
            base.AddObject("CURENCY_TYPE", cURENCY_TYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DISHes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDISHes(DISH dISH)
        {
            base.AddObject("DISHes", dISH);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DISH_TYPE EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDISH_TYPE(DISH_TYPE dISH_TYPE)
        {
            base.AddObject("DISH_TYPE", dISH_TYPE);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PROCESSINGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPROCESSINGs(PROCESSING pROCESSING)
        {
            base.AddObject("PROCESSINGs", pROCESSING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the STATUS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSTATUS(STATUS sTATUS)
        {
            base.AddObject("STATUS", sTATUS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TABLES_INFO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTABLES_INFO(TABLES_INFO tABLES_INFO)
        {
            base.AddObject("TABLES_INFO", tABLES_INFO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WAITER_INFO EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWAITER_INFO(WAITER_INFO wAITER_INFO)
        {
            base.AddObject("WAITER_INFO", wAITER_INFO);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BILLINGs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBILLINGs(BILLING bILLING)
        {
            base.AddObject("BILLINGs", bILLING);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BILLING_DETAIL EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBILLING_DETAIL(BILLING_DETAIL bILLING_DETAIL)
        {
            base.AddObject("BILLING_DETAIL", bILLING_DETAIL);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="BILLING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BILLING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BILLING object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="sELL_DATE">Initial value of the SELL_DATE property.</param>
        /// <param name="mONEY">Initial value of the MONEY property.</param>
        /// <param name="tABLE_ID">Initial value of the TABLE_ID property.</param>
        /// <param name="cHEF_ID">Initial value of the CHEF_ID property.</param>
        public static BILLING CreateBILLING(global::System.Guid id, global::System.DateTime sELL_DATE, global::System.Decimal mONEY, global::System.Guid tABLE_ID, global::System.Guid cHEF_ID)
        {
            BILLING bILLING = new BILLING();
            bILLING.Id = id;
            bILLING.SELL_DATE = sELL_DATE;
            bILLING.MONEY = mONEY;
            bILLING.TABLE_ID = tABLE_ID;
            bILLING.CHEF_ID = cHEF_ID;
            return bILLING;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SELL_DATE
        {
            get
            {
                return _SELL_DATE;
            }
            set
            {
                OnSELL_DATEChanging(value);
                ReportPropertyChanging("SELL_DATE");
                _SELL_DATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SELL_DATE");
                OnSELL_DATEChanged();
            }
        }
        private global::System.DateTime _SELL_DATE;
        partial void OnSELL_DATEChanging(global::System.DateTime value);
        partial void OnSELL_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MONEY
        {
            get
            {
                return _MONEY;
            }
            set
            {
                OnMONEYChanging(value);
                ReportPropertyChanging("MONEY");
                _MONEY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONEY");
                OnMONEYChanged();
            }
        }
        private global::System.Decimal _MONEY;
        partial void OnMONEYChanging(global::System.Decimal value);
        partial void OnMONEYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TABLE_ID
        {
            get
            {
                return _TABLE_ID;
            }
            set
            {
                OnTABLE_IDChanging(value);
                ReportPropertyChanging("TABLE_ID");
                _TABLE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TABLE_ID");
                OnTABLE_IDChanged();
            }
        }
        private global::System.Guid _TABLE_ID;
        partial void OnTABLE_IDChanging(global::System.Guid value);
        partial void OnTABLE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CHEF_ID
        {
            get
            {
                return _CHEF_ID;
            }
            set
            {
                OnCHEF_IDChanging(value);
                ReportPropertyChanging("CHEF_ID");
                _CHEF_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHEF_ID");
                OnCHEF_IDChanged();
            }
        }
        private global::System.Guid _CHEF_ID;
        partial void OnCHEF_IDChanging(global::System.Guid value);
        partial void OnCHEF_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "BILLINGBILLING_DETAIL", "BILLING_DETAIL")]
        public EntityCollection<BILLING_DETAIL> BILLING_DETAILS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLING_DETAIL>("SMSContext.BILLINGBILLING_DETAIL", "BILLING_DETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLING_DETAIL>("SMSContext.BILLINGBILLING_DETAIL", "BILLING_DETAIL", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "TABLES_INFOBILLING", "TABLES_INFO")]
        public TABLES_INFO TABLES_INFO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOBILLING", "TABLES_INFO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOBILLING", "TABLES_INFO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TABLES_INFO> TABLES_INFOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOBILLING", "TABLES_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOBILLING", "TABLES_INFO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "CHEF_INFOBILLING", "CHEF_INFO")]
        public CHEF_INFO CHEF_INFO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOBILLING", "CHEF_INFO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOBILLING", "CHEF_INFO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CHEF_INFO> CHEF_INFOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOBILLING", "CHEF_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOBILLING", "CHEF_INFO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="BILLING_DETAIL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BILLING_DETAIL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BILLING_DETAIL object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="aMOUNT">Initial value of the AMOUNT property.</param>
        /// <param name="dISH_ID">Initial value of the DISH_ID property.</param>
        /// <param name="bILL_ID">Initial value of the BILL_ID property.</param>
        public static BILLING_DETAIL CreateBILLING_DETAIL(global::System.Guid id, global::System.Int32 aMOUNT, global::System.Guid dISH_ID, global::System.Guid bILL_ID)
        {
            BILLING_DETAIL bILLING_DETAIL = new BILLING_DETAIL();
            bILLING_DETAIL.Id = id;
            bILLING_DETAIL.AMOUNT = aMOUNT;
            bILLING_DETAIL.DISH_ID = dISH_ID;
            bILLING_DETAIL.BILL_ID = bILL_ID;
            return bILLING_DETAIL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AMOUNT
        {
            get
            {
                return _AMOUNT;
            }
            set
            {
                OnAMOUNTChanging(value);
                ReportPropertyChanging("AMOUNT");
                _AMOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNT");
                OnAMOUNTChanged();
            }
        }
        private global::System.Int32 _AMOUNT;
        partial void OnAMOUNTChanging(global::System.Int32 value);
        partial void OnAMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DISH_ID
        {
            get
            {
                return _DISH_ID;
            }
            set
            {
                OnDISH_IDChanging(value);
                ReportPropertyChanging("DISH_ID");
                _DISH_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DISH_ID");
                OnDISH_IDChanged();
            }
        }
        private global::System.Guid _DISH_ID;
        partial void OnDISH_IDChanging(global::System.Guid value);
        partial void OnDISH_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid BILL_ID
        {
            get
            {
                return _BILL_ID;
            }
            set
            {
                OnBILL_IDChanging(value);
                ReportPropertyChanging("BILL_ID");
                _BILL_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BILL_ID");
                OnBILL_IDChanged();
            }
        }
        private global::System.Guid _BILL_ID;
        partial void OnBILL_IDChanging(global::System.Guid value);
        partial void OnBILL_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "BILLINGBILLING_DETAIL", "BILLING")]
        public BILLING BILLING
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILLING>("SMSContext.BILLINGBILLING_DETAIL", "BILLING").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILLING>("SMSContext.BILLINGBILLING_DETAIL", "BILLING").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<BILLING> BILLINGReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<BILLING>("SMSContext.BILLINGBILLING_DETAIL", "BILLING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<BILLING>("SMSContext.BILLINGBILLING_DETAIL", "BILLING", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "DISHBILLING_DETAIL", "DISH")]
        public DISH DISH
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH>("SMSContext.DISHBILLING_DETAIL", "DISH").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH>("SMSContext.DISHBILLING_DETAIL", "DISH").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DISH> DISHReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH>("SMSContext.DISHBILLING_DETAIL", "DISH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DISH>("SMSContext.DISHBILLING_DETAIL", "DISH", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="CHEF_INFO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHEF_INFO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CHEF_INFO object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static CHEF_INFO CreateCHEF_INFO(global::System.Guid id, global::System.String nAME)
        {
            CHEF_INFO cHEF_INFO = new CHEF_INFO();
            cHEF_INFO.Id = id;
            cHEF_INFO.NAME = nAME;
            return cHEF_INFO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BIRTHDAY
        {
            get
            {
                return _BIRTHDAY;
            }
            set
            {
                OnBIRTHDAYChanging(value);
                ReportPropertyChanging("BIRTHDAY");
                _BIRTHDAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIRTHDAY");
                OnBIRTHDAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _BIRTHDAY;
        partial void OnBIRTHDAYChanging(Nullable<global::System.DateTime> value);
        partial void OnBIRTHDAYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "CHEF_INFOBILLING", "BILLING")]
        public EntityCollection<BILLING> BILLINGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLING>("SMSContext.CHEF_INFOBILLING", "BILLING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLING>("SMSContext.CHEF_INFOBILLING", "BILLING", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "CHEF_INFOPROCESSING", "PROCESSING")]
        public EntityCollection<PROCESSING> PROCESSINGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PROCESSING>("SMSContext.CHEF_INFOPROCESSING", "PROCESSING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PROCESSING>("SMSContext.CHEF_INFOPROCESSING", "PROCESSING", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="CURENCY_TYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CURENCY_TYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CURENCY_TYPE object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static CURENCY_TYPE CreateCURENCY_TYPE(global::System.Guid id, global::System.String nAME)
        {
            CURENCY_TYPE cURENCY_TYPE = new CURENCY_TYPE();
            cURENCY_TYPE.Id = id;
            cURENCY_TYPE.NAME = nAME;
            return cURENCY_TYPE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="DISH")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DISH : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DISH object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cODE">Initial value of the CODE property.</param>
        /// <param name="nAME_VN">Initial value of the NAME_VN property.</param>
        /// <param name="dISHTYPE_ID">Initial value of the DISHTYPE_ID property.</param>
        /// <param name="pRICE">Initial value of the PRICE property.</param>
        /// <param name="cURENCYTYPE_ID">Initial value of the CURENCYTYPE_ID property.</param>
        public static DISH CreateDISH(global::System.Guid id, global::System.String cODE, global::System.String nAME_VN, global::System.Guid dISHTYPE_ID, global::System.Decimal pRICE, global::System.Guid cURENCYTYPE_ID)
        {
            DISH dISH = new DISH();
            dISH.Id = id;
            dISH.CODE = cODE;
            dISH.NAME_VN = nAME_VN;
            dISH.DISHTYPE_ID = dISHTYPE_ID;
            dISH.PRICE = pRICE;
            dISH.CURENCYTYPE_ID = cURENCYTYPE_ID;
            return dISH;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME_VN
        {
            get
            {
                return _NAME_VN;
            }
            set
            {
                OnNAME_VNChanging(value);
                ReportPropertyChanging("NAME_VN");
                _NAME_VN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME_VN");
                OnNAME_VNChanged();
            }
        }
        private global::System.String _NAME_VN;
        partial void OnNAME_VNChanging(global::System.String value);
        partial void OnNAME_VNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME_EN
        {
            get
            {
                return _NAME_EN;
            }
            set
            {
                OnNAME_ENChanging(value);
                ReportPropertyChanging("NAME_EN");
                _NAME_EN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME_EN");
                OnNAME_ENChanged();
            }
        }
        private global::System.String _NAME_EN;
        partial void OnNAME_ENChanging(global::System.String value);
        partial void OnNAME_ENChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DISHTYPE_ID
        {
            get
            {
                return _DISHTYPE_ID;
            }
            set
            {
                OnDISHTYPE_IDChanging(value);
                ReportPropertyChanging("DISHTYPE_ID");
                _DISHTYPE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DISHTYPE_ID");
                OnDISHTYPE_IDChanged();
            }
        }
        private global::System.Guid _DISHTYPE_ID;
        partial void OnDISHTYPE_IDChanging(global::System.Guid value);
        partial void OnDISHTYPE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PRICE
        {
            get
            {
                return _PRICE;
            }
            set
            {
                OnPRICEChanging(value);
                ReportPropertyChanging("PRICE");
                _PRICE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRICE");
                OnPRICEChanged();
            }
        }
        private global::System.Decimal _PRICE;
        partial void OnPRICEChanging(global::System.Decimal value);
        partial void OnPRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CURENCYTYPE_ID
        {
            get
            {
                return _CURENCYTYPE_ID;
            }
            set
            {
                OnCURENCYTYPE_IDChanging(value);
                ReportPropertyChanging("CURENCYTYPE_ID");
                _CURENCYTYPE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CURENCYTYPE_ID");
                OnCURENCYTYPE_IDChanged();
            }
        }
        private global::System.Guid _CURENCYTYPE_ID;
        partial void OnCURENCYTYPE_IDChanging(global::System.Guid value);
        partial void OnCURENCYTYPE_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "DISH_TYPEDISH", "DISH_TYPE")]
        public DISH_TYPE DISH_TYPE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH_TYPE>("SMSContext.DISH_TYPEDISH", "DISH_TYPE").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH_TYPE>("SMSContext.DISH_TYPEDISH", "DISH_TYPE").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DISH_TYPE> DISH_TYPEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DISH_TYPE>("SMSContext.DISH_TYPEDISH", "DISH_TYPE");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DISH_TYPE>("SMSContext.DISH_TYPEDISH", "DISH_TYPE", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "DISHBILLING_DETAIL", "BILLING_DETAIL")]
        public EntityCollection<BILLING_DETAIL> BILLING_DETAIL
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLING_DETAIL>("SMSContext.DISHBILLING_DETAIL", "BILLING_DETAIL");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLING_DETAIL>("SMSContext.DISHBILLING_DETAIL", "BILLING_DETAIL", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="DISH_TYPE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DISH_TYPE : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DISH_TYPE object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static DISH_TYPE CreateDISH_TYPE(global::System.Guid id, global::System.String nAME)
        {
            DISH_TYPE dISH_TYPE = new DISH_TYPE();
            dISH_TYPE.Id = id;
            dISH_TYPE.NAME = nAME;
            return dISH_TYPE;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "DISH_TYPEDISH", "DISH")]
        public EntityCollection<DISH> DISHES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DISH>("SMSContext.DISH_TYPEDISH", "DISH");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DISH>("SMSContext.DISH_TYPEDISH", "DISH", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="PROCESSING")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PROCESSING : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PROCESSING object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dISH_ID">Initial value of the DISH_ID property.</param>
        /// <param name="pRIORITY">Initial value of the PRIORITY property.</param>
        /// <param name="aMOUNT">Initial value of the AMOUNT property.</param>
        /// <param name="sTATUS_ID">Initial value of the STATUS_ID property.</param>
        /// <param name="tALBLE_ID">Initial value of the TALBLE_ID property.</param>
        /// <param name="cHEF_ID">Initial value of the CHEF_ID property.</param>
        public static PROCESSING CreatePROCESSING(global::System.Guid id, global::System.Guid dISH_ID, global::System.Int32 pRIORITY, global::System.Int32 aMOUNT, global::System.Guid sTATUS_ID, global::System.Guid tALBLE_ID, global::System.Guid cHEF_ID)
        {
            PROCESSING pROCESSING = new PROCESSING();
            pROCESSING.Id = id;
            pROCESSING.DISH_ID = dISH_ID;
            pROCESSING.PRIORITY = pRIORITY;
            pROCESSING.AMOUNT = aMOUNT;
            pROCESSING.STATUS_ID = sTATUS_ID;
            pROCESSING.TALBLE_ID = tALBLE_ID;
            pROCESSING.CHEF_ID = cHEF_ID;
            return pROCESSING;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid DISH_ID
        {
            get
            {
                return _DISH_ID;
            }
            set
            {
                OnDISH_IDChanging(value);
                ReportPropertyChanging("DISH_ID");
                _DISH_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DISH_ID");
                OnDISH_IDChanged();
            }
        }
        private global::System.Guid _DISH_ID;
        partial void OnDISH_IDChanging(global::System.Guid value);
        partial void OnDISH_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PRIORITY
        {
            get
            {
                return _PRIORITY;
            }
            set
            {
                OnPRIORITYChanging(value);
                ReportPropertyChanging("PRIORITY");
                _PRIORITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PRIORITY");
                OnPRIORITYChanged();
            }
        }
        private global::System.Int32 _PRIORITY;
        partial void OnPRIORITYChanging(global::System.Int32 value);
        partial void OnPRIORITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AMOUNT
        {
            get
            {
                return _AMOUNT;
            }
            set
            {
                OnAMOUNTChanging(value);
                ReportPropertyChanging("AMOUNT");
                _AMOUNT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AMOUNT");
                OnAMOUNTChanged();
            }
        }
        private global::System.Int32 _AMOUNT;
        partial void OnAMOUNTChanging(global::System.Int32 value);
        partial void OnAMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid STATUS_ID
        {
            get
            {
                return _STATUS_ID;
            }
            set
            {
                OnSTATUS_IDChanging(value);
                ReportPropertyChanging("STATUS_ID");
                _STATUS_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STATUS_ID");
                OnSTATUS_IDChanged();
            }
        }
        private global::System.Guid _STATUS_ID;
        partial void OnSTATUS_IDChanging(global::System.Guid value);
        partial void OnSTATUS_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMMENT
        {
            get
            {
                return _COMMENT;
            }
            set
            {
                OnCOMMENTChanging(value);
                ReportPropertyChanging("COMMENT");
                _COMMENT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("COMMENT");
                OnCOMMENTChanged();
            }
        }
        private global::System.String _COMMENT;
        partial void OnCOMMENTChanging(global::System.String value);
        partial void OnCOMMENTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid TALBLE_ID
        {
            get
            {
                return _TALBLE_ID;
            }
            set
            {
                OnTALBLE_IDChanging(value);
                ReportPropertyChanging("TALBLE_ID");
                _TALBLE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TALBLE_ID");
                OnTALBLE_IDChanged();
            }
        }
        private global::System.Guid _TALBLE_ID;
        partial void OnTALBLE_IDChanging(global::System.Guid value);
        partial void OnTALBLE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CHEF_ID
        {
            get
            {
                return _CHEF_ID;
            }
            set
            {
                OnCHEF_IDChanging(value);
                ReportPropertyChanging("CHEF_ID");
                _CHEF_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHEF_ID");
                OnCHEF_IDChanged();
            }
        }
        private global::System.Guid _CHEF_ID;
        partial void OnCHEF_IDChanging(global::System.Guid value);
        partial void OnCHEF_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "STATUSPROCESSING", "STATUS")]
        public STATUS STATUSE
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STATUS>("SMSContext.STATUSPROCESSING", "STATUS").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STATUS>("SMSContext.STATUSPROCESSING", "STATUS").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<STATUS> STATUSEReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<STATUS>("SMSContext.STATUSPROCESSING", "STATUS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<STATUS>("SMSContext.STATUSPROCESSING", "STATUS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "TABLES_INFOPROCESSING", "TABLES_INFO")]
        public TABLES_INFO TABLES_INFO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOPROCESSING", "TABLES_INFO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOPROCESSING", "TABLES_INFO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TABLES_INFO> TABLES_INFOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOPROCESSING", "TABLES_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TABLES_INFO>("SMSContext.TABLES_INFOPROCESSING", "TABLES_INFO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "CHEF_INFOPROCESSING", "CHEF_INFO")]
        public CHEF_INFO CHEF_INFO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOPROCESSING", "CHEF_INFO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOPROCESSING", "CHEF_INFO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CHEF_INFO> CHEF_INFOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOPROCESSING", "CHEF_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CHEF_INFO>("SMSContext.CHEF_INFOPROCESSING", "CHEF_INFO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="STATUS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class STATUS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new STATUS object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static STATUS CreateSTATUS(global::System.Guid id, global::System.String nAME)
        {
            STATUS sTATUS = new STATUS();
            sTATUS.Id = id;
            sTATUS.NAME = nAME;
            return sTATUS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "STATUSPROCESSING", "PROCESSING")]
        public EntityCollection<PROCESSING> PROCESSINGS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PROCESSING>("SMSContext.STATUSPROCESSING", "PROCESSING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PROCESSING>("SMSContext.STATUSPROCESSING", "PROCESSING", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="TABLES_INFO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TABLES_INFO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TABLES_INFO object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cODE">Initial value of the CODE property.</param>
        /// <param name="wAITER_ID">Initial value of the WAITER_ID property.</param>
        public static TABLES_INFO CreateTABLES_INFO(global::System.Guid id, global::System.String cODE, global::System.Guid wAITER_ID)
        {
            TABLES_INFO tABLES_INFO = new TABLES_INFO();
            tABLES_INFO.Id = id;
            tABLES_INFO.CODE = cODE;
            tABLES_INFO.WAITER_ID = wAITER_ID;
            return tABLES_INFO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CODE
        {
            get
            {
                return _CODE;
            }
            set
            {
                OnCODEChanging(value);
                ReportPropertyChanging("CODE");
                _CODE = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CODE");
                OnCODEChanged();
            }
        }
        private global::System.String _CODE;
        partial void OnCODEChanging(global::System.String value);
        partial void OnCODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid WAITER_ID
        {
            get
            {
                return _WAITER_ID;
            }
            set
            {
                OnWAITER_IDChanging(value);
                ReportPropertyChanging("WAITER_ID");
                _WAITER_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WAITER_ID");
                OnWAITER_IDChanged();
            }
        }
        private global::System.Guid _WAITER_ID;
        partial void OnWAITER_IDChanging(global::System.Guid value);
        partial void OnWAITER_IDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "TABLES_INFOPROCESSING", "PROCESSING")]
        public EntityCollection<PROCESSING> PROCESSINGS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PROCESSING>("SMSContext.TABLES_INFOPROCESSING", "PROCESSING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PROCESSING>("SMSContext.TABLES_INFOPROCESSING", "PROCESSING", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "WAITER_INFOTABLES_INFO", "WAITER_INFO")]
        public WAITER_INFO WAITER_INFO
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WAITER_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "WAITER_INFO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WAITER_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "WAITER_INFO").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<WAITER_INFO> WAITER_INFOReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<WAITER_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "WAITER_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<WAITER_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "WAITER_INFO", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "TABLES_INFOBILLING", "BILLING")]
        public EntityCollection<BILLING> BILLINGs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BILLING>("SMSContext.TABLES_INFOBILLING", "BILLING");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BILLING>("SMSContext.TABLES_INFOBILLING", "BILLING", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SMSContext", Name="WAITER_INFO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WAITER_INFO : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WAITER_INFO object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nAME">Initial value of the NAME property.</param>
        public static WAITER_INFO CreateWAITER_INFO(global::System.Guid id, global::System.String nAME)
        {
            WAITER_INFO wAITER_INFO = new WAITER_INFO();
            wAITER_INFO.Id = id;
            wAITER_INFO.NAME = nAME;
            return wAITER_INFO;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BIRTHDAY
        {
            get
            {
                return _BIRTHDAY;
            }
            set
            {
                OnBIRTHDAYChanging(value);
                ReportPropertyChanging("BIRTHDAY");
                _BIRTHDAY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIRTHDAY");
                OnBIRTHDAYChanged();
            }
        }
        private Nullable<global::System.DateTime> _BIRTHDAY;
        partial void OnBIRTHDAYChanging(Nullable<global::System.DateTime> value);
        partial void OnBIRTHDAYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PHONE
        {
            get
            {
                return _PHONE;
            }
            set
            {
                OnPHONEChanging(value);
                ReportPropertyChanging("PHONE");
                _PHONE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PHONE");
                OnPHONEChanged();
            }
        }
        private global::System.String _PHONE;
        partial void OnPHONEChanging(global::System.String value);
        partial void OnPHONEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SMSContext", "WAITER_INFOTABLES_INFO", "TABLES_INFO")]
        public EntityCollection<TABLES_INFO> TABLES_INFOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TABLES_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "TABLES_INFO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TABLES_INFO>("SMSContext.WAITER_INFOTABLES_INFO", "TABLES_INFO", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
